# Generated by Django 4.0.5 on 2022-06-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_categorie_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
