# Generated by Django 4.0.5 on 2022-06-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0006_alter_idea_description_userlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='nom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
