# Generated by Django 4.0.5 on 2022-06-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0008_idea_user_alter_idea_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='modified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ModifiedIdeas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.categorie'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.theme'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
